const Description = require('./index.js');


const itemData = [
  {
    itemId: '100',
    title: 'CatToys Spring-Loaded Mouse',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3419054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Brown',
    material: 'Plush',
    length: '5 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '101',
    title: 'BestFriends Dog Bone',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3445910',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'White',
    material: 'Bone',
    length: '7 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '102',
    title: 'CatToys Springy Bird Toy',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '7619054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush and Wire',
    length: '10 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '103',
    title: 'Bird Watcher Bird Cage Mirror, 4" L X 2.5" W',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '8949054',
    primaryBrand: 'Bird Watcher',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Green',
    material: 'Plastic',
    length: '4 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '104',
    title: 'BestFriends Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '105',
    title: 'IpsumLorem Plush Bunny with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'IpsumLorum',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '106',
    title: 'BestFriends Plush Mouse with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '1282048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '107',
    title: 'IpsumLorem BirdCage Swing',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3456748',
    primaryBrand: 'IpsumLorem',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plastic',
    length: '4 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '108',
    title: 'KittyBrand Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'KittyBrand',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '109',
    title: 'BestFriends Rubber Bone with Chicken Flavor',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '2342048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '8 IN',
    width: '2 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '110',
    title: 'CatToys Spring-Loaded Mouse',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3419054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Brown',
    material: 'Plush',
    length: '5 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '111',
    title: 'BestFriends Dog Bone',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3445910',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'White',
    material: 'Bone',
    length: '7 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '112',
    title: 'CatToys Springy Bird Toy',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '7619054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush and Wire',
    length: '10 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '113',
    title: 'Bird Watcher Bird Cage Mirror, 4" L X 2.5" W',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '8949054',
    primaryBrand: 'Bird Watcher',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Green',
    material: 'Plastic',
    length: '4 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '114',
    title: 'BestFriends Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '115',
    title: 'IpsumLorem Plush Bunny with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'IpsumLorum',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '116',
    title: 'BestFriends Plush Mouse with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '1282048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '117',
    title: 'IpsumLorem BirdCage Swing',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3456748',
    primaryBrand: 'IpsumLorem',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plastic',
    length: '4 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '118',
    title: 'KittyBrand Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'KittyBrand',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '119',
    title: 'BestFriends Rubber Bone with Chicken Flavor',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '2342048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '8 IN',
    width: '2 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '120',
    title: 'CatToys Spring-Loaded Mouse',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3419054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Brown',
    material: 'Plush',
    length: '5 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '121',
    title: 'BestFriends Dog Bone',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3445910',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'White',
    material: 'Bone',
    length: '7 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '122',
    title: 'CatToys Springy Bird Toy',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '7619054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush and Wire',
    length: '10 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '123',
    title: 'Bird Watcher Bird Cage Mirror, 4" L X 2.5" W',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '8949054',
    primaryBrand: 'Bird Watcher',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Green',
    material: 'Plastic',
    length: '4 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '124',
    title: 'BestFriends Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '125',
    title: 'IpsumLorem Plush Bunny with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'IpsumLorum',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '126',
    title: 'BestFriends Plush Mouse with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '1282048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '127',
    title: 'IpsumLorem BirdCage Swing',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3456748',
    primaryBrand: 'IpsumLorem',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plastic',
    length: '4 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '128',
    title: 'KittyBrand Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'KittyBrand',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '129',
    title: 'BestFriends Rubber Bone with Chicken Flavor',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '2342048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '8 IN',
    width: '2 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '130',
    title: 'CatToys Spring-Loaded Mouse',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3419054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Brown',
    material: 'Plush',
    length: '5 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '131',
    title: 'BestFriends Dog Bone',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3445910',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'White',
    material: 'Bone',
    length: '7 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '132',
    title: 'CatToys Springy Bird Toy',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '7619054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush and Wire',
    length: '10 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '133',
    title: 'Bird Watcher Bird Cage Mirror, 4" L X 2.5" W',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '8949054',
    primaryBrand: 'Bird Watcher',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Green',
    material: 'Plastic',
    length: '4 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '134',
    title: 'BestFriends Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '135',
    title: 'IpsumLorem Plush Bunny with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'IpsumLorum',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '136',
    title: 'BestFriends Plush Mouse with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '1282048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '137',
    title: 'IpsumLorem BirdCage Swing',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3456748',
    primaryBrand: 'IpsumLorem',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plastic',
    length: '4 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '138',
    title: 'KittyBrand Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'KittyBrand',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '139',
    title: 'BestFriends Rubber Bone with Chicken Flavor',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '2342048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '8 IN',
    width: '2 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '140',
    title: 'CatToys Spring-Loaded Mouse',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3419054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Brown',
    material: 'Plush',
    length: '5 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '141',
    title: 'BestFriends Dog Bone',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3445910',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'White',
    material: 'Bone',
    length: '7 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '142',
    title: 'CatToys Springy Bird Toy',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '7619054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush and Wire',
    length: '10 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '143',
    title: 'Bird Watcher Bird Cage Mirror, 4" L X 2.5" W',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '8949054',
    primaryBrand: 'Bird Watcher',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Green',
    material: 'Plastic',
    length: '4 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '144',
    title: 'BestFriends Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '145',
    title: 'IpsumLorem Plush Bunny with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'IpsumLorum',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '146',
    title: 'BestFriends Plush Mouse with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '1282048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '147',
    title: 'IpsumLorem BirdCage Swing',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3456748',
    primaryBrand: 'IpsumLorem',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plastic',
    length: '4 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '148',
    title: 'KittyBrand Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'KittyBrand',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '149',
    title: 'BestFriends Rubber Bone with Chicken Flavor',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '2342048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '8 IN',
    width: '2 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '150',
    title: 'CatToys Spring-Loaded Mouse',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3419054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Brown',
    material: 'Plush',
    length: '5 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '151',
    title: 'BestFriends Dog Bone',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3445910',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'White',
    material: 'Bone',
    length: '7 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '152',
    title: 'CatToys Springy Bird Toy',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '7619054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush and Wire',
    length: '10 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '153',
    title: 'Bird Watcher Bird Cage Mirror, 4" L X 2.5" W',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '8949054',
    primaryBrand: 'Bird Watcher',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Green',
    material: 'Plastic',
    length: '4 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '154',
    title: 'BestFriends Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '155',
    title: 'IpsumLorem Plush Bunny with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'IpsumLorum',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '156',
    title: 'BestFriends Plush Mouse with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '1282048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '157',
    title: 'IpsumLorem BirdCage Swing',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3456748',
    primaryBrand: 'IpsumLorem',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plastic',
    length: '4 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '158',
    title: 'KittyBrand Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'KittyBrand',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '159',
    title: 'BestFriends Rubber Bone with Chicken Flavor',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '2342048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '8 IN',
    width: '2 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '160',
    title: 'CatToys Spring-Loaded Mouse',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3419054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Brown',
    material: 'Plush',
    length: '5 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '161',
    title: 'BestFriends Dog Bone',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3445910',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'White',
    material: 'Bone',
    length: '7 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '162',
    title: 'CatToys Springy Bird Toy',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '7619054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush and Wire',
    length: '10 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '163',
    title: 'Bird Watcher Bird Cage Mirror, 4" L X 2.5" W',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '8949054',
    primaryBrand: 'Bird Watcher',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Green',
    material: 'Plastic',
    length: '4 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '164',
    title: 'BestFriends Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '165',
    title: 'IpsumLorem Plush Bunny with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'IpsumLorum',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '166',
    title: 'BestFriends Plush Mouse with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '1282048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '167',
    title: 'IpsumLorem BirdCage Swing',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3456748',
    primaryBrand: 'IpsumLorem',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plastic',
    length: '4 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '168',
    title: 'KittyBrand Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'KittyBrand',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '169',
    title: 'BestFriends Rubber Bone with Chicken Flavor',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '2342048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '8 IN',
    width: '2 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '170',
    title: 'CatToys Spring-Loaded Mouse',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3419054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Brown',
    material: 'Plush',
    length: '5 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '171',
    title: 'BestFriends Dog Bone',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3445910',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'White',
    material: 'Bone',
    length: '7 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '172',
    title: 'CatToys Springy Bird Toy',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '7619054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush and Wire',
    length: '10 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '173',
    title: 'Bird Watcher Bird Cage Mirror, 4" L X 2.5" W',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '8949054',
    primaryBrand: 'Bird Watcher',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Green',
    material: 'Plastic',
    length: '4 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '174',
    title: 'BestFriends Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '175',
    title: 'IpsumLorem Plush Bunny with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'IpsumLorum',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '176',
    title: 'BestFriends Plush Mouse with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '1282048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '177',
    title: 'IpsumLorem BirdCage Swing',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3456748',
    primaryBrand: 'IpsumLorem',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plastic',
    length: '4 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '178',
    title: 'KittyBrand Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'KittyBrand',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '179',
    title: 'BestFriends Rubber Bone with Chicken Flavor',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '2342048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '8 IN',
    width: '2 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '180',
    title: 'CatToys Spring-Loaded Mouse',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3419054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Brown',
    material: 'Plush',
    length: '5 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '181',
    title: 'BestFriends Dog Bone',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3445910',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'White',
    material: 'Bone',
    length: '7 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '182',
    title: 'CatToys Springy Bird Toy',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '7619054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush and Wire',
    length: '10 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '183',
    title: 'Bird Watcher Bird Cage Mirror, 4" L X 2.5" W',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '8949054',
    primaryBrand: 'Bird Watcher',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Green',
    material: 'Plastic',
    length: '4 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '184',
    title: 'BestFriends Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '185',
    title: 'IpsumLorem Plush Bunny with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'IpsumLorum',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '186',
    title: 'BestFriends Plush Mouse with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '1282048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '187',
    title: 'IpsumLorem BirdCage Swing',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3456748',
    primaryBrand: 'IpsumLorem',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plastic',
    length: '4 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '188',
    title: 'KittyBrand Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'KittyBrand',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '189',
    title: 'BestFriends Rubber Bone with Chicken Flavor',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '2342048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '8 IN',
    width: '2 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '190',
    title: 'CatToys Spring-Loaded Mouse',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3419054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Brown',
    material: 'Plush',
    length: '5 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '191',
    title: 'BestFriends Dog Bone',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3445910',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'White',
    material: 'Bone',
    length: '7 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '192',
    title: 'CatToys Springy Bird Toy',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '7619054',
    primaryBrand: 'CatToys',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush and Wire',
    length: '10 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '193',
    title: 'Bird Watcher Bird Cage Mirror, 4" L X 2.5" W',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '8949054',
    primaryBrand: 'Bird Watcher',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Green',
    material: 'Plastic',
    length: '4 IN',
    width: '2.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '194',
    title: 'BestFriends Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '195',
    title: 'IpsumLorem Plush Bunny with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'IpsumLorum',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '196',
    title: 'BestFriends Plush Mouse with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '1282048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '197',
    title: 'IpsumLorem BirdCage Swing',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '3456748',
    primaryBrand: 'IpsumLorem',
    daysToShip: 'Ships Next Business Day',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on birds playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plastic',
    length: '4 IN',
    width: '1.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '198',
    title: 'KittyBrand Plush Fox with Squeaker',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '9582048',
    primaryBrand: 'KittyBrand',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on cats playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '6 IN',
    width: '4.5 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  },
  {
    itemId: '199',
    title: 'BestFriends Rubber Bone with Chicken Flavor',
    description: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    SKU: '2342048',
    primaryBrand: 'BestFriends',
    daysToShip: 'Ships In Two Business Days',
    directions: 'CAUTION: Intended for pet use only. Not a childs toy. Choose toys based on dogs playing habits. Toys should be large enough to not be swallowed. IMPORTANT: No pet toy is indestructible. Small parts present a choking or gastrointestinal blockage risk. Always supervise your pet during play to prevent accidental swallowing of parts. Inspsect toy regularly and replace if any part becomes loose. If toy becomes wet, some color transfer may occur. Spot clean only.',
    primaryColor: 'Multicolor',
    material: 'Plush',
    length: '8 IN',
    width: '2 IN',
    additionalDetails: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit.'
  }
];

const insertItemData = () => {
  Description.create(itemData)
  .then(() => {
    console.log('DB seeded');
  })
}

insertItemData();